version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: marketplace_freelance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./backend/src/main/resources/data.sql:/docker-entrypoint-initdb.d/02-data.sql:ro
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/marketplace_freelance
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      JWT_SECRET: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  db-data:
    driver: local
