import type { Category, FreelancerProfile, Service } from "./types";

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name: "Design graphique", description: "Logos, identité visuelle, affiches" },
  { id: 2, name: "Développement web", description: "Sites, apps, intégrations" },
  { id: 3, name: "Photographie", description: "Événementiel, produit, portrait" },
  { id: 4, name: "Montage vidéo", description: "Reels, mariage, corporate" },
  { id: 5, name: "Cours particuliers", description: "Soutien scolaire, langues" },
  { id: 6, name: "Réparation informatique", description: "PC, mobile, réseau" },
  { id: 7, name: "Rédaction", description: "Articles, copywriting, traduction" },
  { id: 8, name: "Community management", description: "Réseaux sociaux, contenu" },
];

export const MOCK_FREELANCERS: FreelancerProfile[] = [
  {
    id: 1,
    userId: 101,
    firstName: "Yassine",
    lastName: "El Amrani",
    city: "Fès",
    bio: "Designer graphique avec 6 ans d'expérience. Spécialiste identité visuelle et branding pour PME locales.",
    skills: ["Logo", "Branding", "Illustrator", "Figma"],
    hourlyRate: 180,
    experienceYears: 6,
    averageRating: 4.9,
    totalReviews: 47,
    availabilityStatus: "AVAILABLE",
  },
  {
    id: 2,
    userId: 102,
    firstName: "Salma",
    lastName: "Benali",
    city: "Casablanca",
    bio: "Développeuse full-stack React + Spring Boot. J'aide les startups locales à lancer leur MVP rapidement.",
    skills: ["React", "Spring Boot", "PostgreSQL", "TypeScript"],
    hourlyRate: 250,
    experienceYears: 4,
    averageRating: 4.8,
    totalReviews: 32,
    availabilityStatus: "AVAILABLE",
  },
  {
    id: 3,
    userId: 103,
    firstName: "Omar",
    lastName: "Tazi",
    city: "Rabat",
    bio: "Photographe événementiel. Mariages, corporate, portrait studio. Matériel professionnel.",
    skills: ["Mariage", "Portrait", "Lightroom", "Studio"],
    hourlyRate: 350,
    experienceYears: 8,
    averageRating: 5.0,
    totalReviews: 89,
    availabilityStatus: "BUSY",
  },
  {
    id: 4,
    userId: 104,
    firstName: "Imane",
    lastName: "Chakir",
    city: "Marrakech",
    bio: "Monteuse vidéo passionnée. Reels, contenus TikTok, vidéos corporate et mariages.",
    skills: ["Premiere Pro", "After Effects", "Color grading"],
    hourlyRate: 200,
    experienceYears: 3,
    averageRating: 4.7,
    totalReviews: 21,
    availabilityStatus: "AVAILABLE",
  },
  {
    id: 5,
    userId: 105,
    firstName: "Karim",
    lastName: "Bennis",
    city: "Tanger",
    bio: "Professeur de mathématiques et physique, soutien scolaire collège et lycée à domicile ou en ligne.",
    skills: ["Maths", "Physique", "Bac", "Lycée"],
    hourlyRate: 120,
    experienceYears: 10,
    averageRating: 4.9,
    totalReviews: 64,
    availabilityStatus: "AVAILABLE",
  },
  {
    id: 6,
    userId: 106,
    firstName: "Nadia",
    lastName: "Idrissi",
    city: "Fès",
    bio: "Community manager bilingue FR/AR. Stratégie de contenu, calendrier éditorial et création visuelle.",
    skills: ["Instagram", "TikTok", "Canva", "Stratégie"],
    hourlyRate: 150,
    experienceYears: 5,
    averageRating: 4.8,
    totalReviews: 38,
    availabilityStatus: "AVAILABLE",
  },
];

export const MOCK_SERVICES: Service[] = [
  {
    id: 1,
    freelancerId: 1,
    freelancer: {
      id: 1,
      firstName: "Yassine",
      lastName: "El Amrani",
      city: "Fès",
      averageRating: 4.9,
      totalReviews: 47,
    },
    categoryId: 1,
    category: MOCK_CATEGORIES[0],
    title: "Création de logo professionnel + charte graphique",
    description:
      "Je crée un logo unique et mémorable pour votre marque, accompagné d'une charte graphique complète (couleurs, typographies, déclinaisons).",
    price: 1200,
    deliveryTime: 5,
    city: "Fès",
    isActive: true,
  },
  {
    id: 2,
    freelancerId: 2,
    freelancer: {
      id: 2,
      firstName: "Salma",
      lastName: "Benali",
      city: "Casablanca",
      averageRating: 4.8,
      totalReviews: 32,
    },
    categoryId: 2,
    category: MOCK_CATEGORIES[1],
    title: "Site vitrine React responsive + déploiement",
    description:
      "Site vitrine moderne en React avec design responsive, optimisé SEO. Hébergement et déploiement inclus.",
    price: 3500,
    deliveryTime: 10,
    city: "Casablanca",
    isActive: true,
  },
  {
    id: 3,
    freelancerId: 3,
    freelancer: {
      id: 3,
      firstName: "Omar",
      lastName: "Tazi",
      city: "Rabat",
      averageRating: 5.0,
      totalReviews: 89,
    },
    categoryId: 3,
    category: MOCK_CATEGORIES[2],
    title: "Reportage photo mariage — journée complète",
    description:
      "Couverture photo professionnelle de votre mariage, de la préparation à la soirée. 300+ photos retouchées livrées en 2 semaines.",
    price: 4500,
    deliveryTime: 14,
    city: "Rabat",
    isActive: true,
  },
  {
    id: 4,
    freelancerId: 4,
    freelancer: {
      id: 4,
      firstName: "Imane",
      lastName: "Chakir",
      city: "Marrakech",
      averageRating: 4.7,
      totalReviews: 21,
    },
    categoryId: 4,
    category: MOCK_CATEGORIES[3],
    title: "Pack 5 reels Instagram montés et optimisés",
    description: "Montage dynamique de 5 reels pour Instagram/TikTok à partir de vos rushes, avec sous-titres et musique.",
    price: 800,
    deliveryTime: 4,
    city: "Marrakech",
    isActive: true,
  },
  {
    id: 5,
    freelancerId: 5,
    freelancer: {
      id: 5,
      firstName: "Karim",
      lastName: "Bennis",
      city: "Tanger",
      averageRating: 4.9,
      totalReviews: 64,
    },
    categoryId: 5,
    category: MOCK_CATEGORIES[4],
    title: "Cours particuliers de maths — niveau lycée",
    description: "Soutien scolaire en mathématiques pour lycéens, à domicile à Tanger ou en ligne. 1h30 par séance.",
    price: 180,
    deliveryTime: 1,
    city: "Tanger",
    isActive: true,
  },
  {
    id: 6,
    freelancerId: 6,
    freelancer: {
      id: 6,
      firstName: "Nadia",
      lastName: "Idrissi",
      city: "Fès",
      averageRating: 4.8,
      totalReviews: 38,
    },
    categoryId: 8,
    category: MOCK_CATEGORIES[7],
    title: "Gestion mensuelle Instagram + 12 publications",
    description:
      "Stratégie de contenu, création visuelle et publication de 12 posts/mois sur Instagram. Reporting mensuel inclus.",
    price: 2200,
    deliveryTime: 30,
    city: "Fès",
    isActive: true,
  },
];

export const MOROCCAN_CITIES = [
  "Casablanca",
  "Rabat",
  "Fès",
  "Marrakech",
  "Tanger",
  "Agadir",
  "Meknès",
  "Oujda",
  "Kénitra",
  "Tétouan",
];
